spring:
  datasource:
    url: jdbc:mysql://localhost:3306/winter_admin
    username: root
    password: 123456
  messages:
    basename: i18n/messages
winter:
  jwt:
    path-patterns:
      - /**
    exclude-path-patterns:
      - /static
      - /auth/**
      - /user/**
logging:
  level:
    org.winterframework.admin.dao.mapper: DEBUG
