spring:
  datasource:
    url: jdbc:mysql://localhost:3306/winter_admin
    username: root
    password: 123456
  messages:
    basename: i18n/messages
  mvc:
    servlet:
      path: /api
winter:
  jwt:
    path-patterns:
      - /**
    exclude-path-patterns:
      - /static
      - /auth/**
      - /user/**
      - /routes/**
      - /role/**
      - /permission/**
      - /api/test/**
    token-white-uri-array:
      - /api/test/test
      - /api/error
logging:
  level:
    org.winterframework.admin.dao.mapper: DEBUG
