spring:
  datasource:
    url: jdbc:mysql://localhost:3306/winter_admin
    username: root
    password: 123456
  messages:
    basename: i18n/messages
  mvc:
    servlet:
      path: /api
winter:
  jwt:
    path-patterns:
      - /.*
    exclude-path-patterns:
      - ^/static
      - ^/api/auth/.*
      - ^/api/admin_user/.*
      - ^/api/routes/.*
      - ^/api/role/.*
      - ^/api/permission/.*
      - ^/api/test/.*
    token-white-uris:
      - ^/api/error
      - ^/api/test/.*
logging:
  level:
    org.winterframework.admin.dao.mapper: DEBUG
mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml
dubbo:
  application:
    name: winter-admin
    qos-enable: false
  registry:
    address: zookeeper://localhost:2181
