dubbo:
  application:
    name: winter-admin-provider
    id: winter-admin-provider

  protocol:
    name: dubbo
    port: 20881

  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: org.winterframework.dubbo.provider
spring:
  main:
    web-application-type: none